import type { RecapResponse } from "../types";

interface Props {
  data: RecapResponse;
  onReset: () => void;
}

function formatDate(ddMMyyyy: string): string {
  const [day, month, year] = ddMMyyyy.split("-");
  return new Date(`${year}-${month}-${day}`).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export default function RecapCard({ data, onReset }: Props) {
  const { recap, meta } = data;

  function handleShare() {
    const text = `${recap.headline}\n\n${meta.artist} @ ${meta.venue} — ${formatDate(meta.date)}\n\nGenerated by Setlist AI`;
    if (navigator.share) {
      navigator.share({ title: recap.headline, text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text).then(() => alert("Copied to clipboard!"));
    }
  }

  return (
    <div className="recap-wrapper">
      <div className="recap-card" id="recap-card">
        <header className="recap-header">
          <div className="recap-rating">{recap.concertRating}</div>
          <h1 className="recap-headline">{recap.headline}</h1>
          <div className="recap-meta-row">
            <span className="recap-artist">{meta.artist}</span>
            <span className="recap-sep">·</span>
            <span className="recap-venue">{meta.venue}</span>
            <span className="recap-sep">·</span>
            <span className="recap-date">{formatDate(meta.date)}</span>
          </div>
          {meta.tour && <p className="recap-tour">{meta.tour}</p>}
          <div className="recap-tags">
            {recap.tags.map((tag) => (
              <span key={tag} className="recap-tag">{tag}</span>
            ))}
          </div>
        </header>

        <section className="recap-body">
          <p className="recap-opening">{recap.openingVibe}</p>

          <div className="highlights-section">
            <h2 className="highlights-heading">Moments that mattered</h2>
            <div className="highlights-list">
              {recap.songHighlights.map((h) => (
                <div key={h.songName} className="highlight-item">
                  <div className="highlight-song">"{h.songName}"</div>
                  <p className="highlight-commentary">{h.commentary}</p>
                </div>
              ))}
            </div>
          </div>

          <p className="recap-closing">{recap.closingThought}</p>
        </section>

        <footer className="recap-footer">
          <a
            href={meta.setlistUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="setlist-link"
          >
            Full setlist on setlist.fm ↗
          </a>
          <span className="recap-credit">Generated by Setlist AI</span>
        </footer>
      </div>

      <div className="recap-actions">
        <button className="action-btn share-btn" onClick={handleShare}>
          Share recap
        </button>
        <button className="action-btn reset-btn" onClick={onReset}>
          Search another show
        </button>
      </div>
    </div>
  );
}